# -*- coding: utf-8 -*-
"""order_items.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LUlc_q3KzSgOfeLtzd4r-qiKHzBOUbz
"""

import pandas as pd
import numpy as np

# Đọc file
df_items = pd.read_csv("order_items.csv")

# Đọc thử dữ liệu
df_items.info()
df_items.isna().sum()

# Xoá dòng rỗng hoàn toàn
n_before = len(df_items)
df_items = df_items.dropna(how="all")
print(f"Số dòng rỗng hoàn toàn (đã xoá): {n_before - len(df_items)}")

# Xoá dòng trùng hoàn toàn (mọi cột giống nhau)
n_before = len(df_items)
df_items = df_items.drop_duplicates()
print(f"Số dòng trùng lặp toàn bộ (đã xoá): {n_before - len(df_items)}")

# order_id, product_id là PK/FK bắt buộc -> dòng thiếu thì phải bỏ
n_before = len(df_items)
df_items = df_items.dropna(subset=["order_id", "product_id"])
print(f"Số dòng bị xoá do thiếu order_id/product_id: {n_before - len(df_items)}")

df_items = df_items.reset_index(drop=True)

# Lấp dữ liệu thiếu cho các cột số
if df_items["quantity"].isna().sum() > 0:
    n_missing = df_items["quantity"].isna().sum()
    df_items["quantity"] = df_items["quantity"].fillna(df_items["quantity"].median())
    print(f"quantity thiếu {n_missing} giá trị -> đã lấp bằng median")

if df_items["unit_price"].isna().sum() > 0:
    n_missing = df_items["unit_price"].isna().sum()
    df_items["unit_price"] = df_items["unit_price"].fillna(df_items["unit_price"].median())
    print(f"unit_price thiếu {n_missing} giá trị -> đã lấp bằng median")

# discount_amount: null nghĩa là không giảm giá -> điền 0
n_missing_discount = df_items["discount_amount"].isna().sum()
df_items["discount_amount"] = df_items["discount_amount"].fillna(0)
if n_missing_discount > 0:
    print(f"discount_amount thiếu {n_missing_discount} giá trị -> đã điền 0")

# promo_id, promo_id_2: null là HỢP LỆ (không dùng promo) -> giữ nguyên NaN, không fillna

# GỘP CÁC DÒNG TRÙNG PK (order_id, product_id)
dup_mask = df_items.duplicated(subset=["order_id", "product_id"], keep=False)
n_dup_pk = df_items.duplicated(subset=["order_id", "product_id"]).sum()
if n_dup_pk > 0:
    print(f"Số cặp (order_id, product_id) bị trùng -> sẽ gộp lại: {n_dup_pk} dòng thừa")

    df_dup = df_items[dup_mask]
    df_unique = df_items[~dup_mask]

    def weighted_avg_price(g):
        total_qty = g["quantity"].sum()
        if total_qty == 0:
            return g["unit_price"].mean()
        return (g["unit_price"] * g["quantity"]).sum() / total_qty

    rows = []
    for (oid, pid), g in df_dup.groupby(["order_id", "product_id"]):
        rows.append({
            "order_id": oid,
            "product_id": pid,
            "quantity": g["quantity"].sum(),
            "unit_price": weighted_avg_price(g),
            "discount_amount": g["discount_amount"].sum(),
            "promo_id": g["promo_id"].dropna().iloc[0] if g["promo_id"].notna().any() else np.nan,
            "promo_id_2": g["promo_id_2"].dropna().iloc[0] if g["promo_id_2"].notna().any() else np.nan,
        })
    df_merged = pd.DataFrame(rows)

    df_items = pd.concat([df_unique, df_merged], ignore_index=True)
else:
    print("Không có cặp (order_id, product_id) nào bị trùng")

# Đánh dấu giá trị số bất thường
n_bad_qty = (df_items["quantity"] <= 0).sum()
n_bad_price = (df_items["unit_price"] <= 0).sum()
n_bad_discount = (df_items["discount_amount"] < 0).sum()
print(f"quantity <= 0: {n_bad_qty} | unit_price <= 0: {n_bad_price} | discount_amount < 0: {n_bad_discount}")

# Đối chiếu chéo với các bảng liên quan
try:
    df_orders_ref = pd.read_csv("orders_enriched.csv")
    n_orphan_order = (~df_items["order_id"].isin(df_orders_ref["order_id"])).sum()
    print(f"order_id không tồn tại trong orders_enriched: {n_orphan_order}")
except FileNotFoundError:
    print("Không tìm thấy orders_enriched.csv, bỏ qua đối chiếu order_id")

try:
    df_products_ref = pd.read_csv("products.csv")
    n_orphan_product = (~df_items["product_id"].isin(df_products_ref["product_id"])).sum()
    print(f"product_id không tồn tại trong products: {n_orphan_product}")
except FileNotFoundError:
    print("Không tìm thấy products.csv, bỏ qua đối chiếu product_id")

try:
    df_promo_ref = pd.read_csv("promotions.csv")
    n_bad_promo = (df_items["promo_id"].notna() & ~df_items["promo_id"].isin(df_promo_ref["promo_id"])).sum()
    n_bad_promo2 = (df_items["promo_id_2"].notna() & ~df_items["promo_id_2"].isin(df_promo_ref["promo_id"])).sum()
    print(f"promo_id lạ: {n_bad_promo} | promo_id_2 lạ: {n_bad_promo2}")
except FileNotFoundError:
    print("Không tìm thấy promotions.csv, bỏ qua đối chiếu promo_id")

# Final check
print("=" * 50)
print("KIỂM TRA CUỐI CÙNG")
print("=" * 50)
silver_cols = ["order_id", "product_id", "quantity", "unit_price", "discount_amount", "promo_id", "promo_id_2"]
df_items_silver = df_items[silver_cols].copy()
print(df_items_silver.isna().sum())
print()
print(f"Tổng số dòng: {len(df_items_silver)}")
df_items_silver.head()

# Xuất file csv
df_items_silver.to_csv("order_items.csv", index=False)