# -*- coding: utf-8 -*-
"""orders_enriched.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LUlc_q3KzSgOfeLtzd4r-qiKHzBOUbz
"""

import pandas as pd
import numpy as np

# Đọc file
df_orders = pd.read_csv("orders_enriched.csv")
df_orders.columns = [c.strip().lower() for c in df_orders.columns]

# Đọc thử dữ liệu
df_orders.info()
df_orders.isna().sum()

# Xoá dòng rỗng hoàn toàn
n_before = len(df_orders)
df_orders = df_orders.dropna(how="all")
print(f"Số dòng rỗng hoàn toàn (đã xoá): {n_before - len(df_orders)}")

# Xoá dòng trùng hoàn toàn (mọi cột giống nhau)
n_before = len(df_orders)
df_orders = df_orders.drop_duplicates()
print(f"Số dòng trùng lặp toàn bộ (đã xoá): {n_before - len(df_orders)}")

# order_id là PK -> dòng thiếu PK buộc phải xoá; trùng PK giữ bản đầu
n_before = len(df_orders)
df_orders = df_orders.dropna(subset=["order_id"])
df_orders = df_orders.drop_duplicates(subset="order_id", keep="first")
print(f"Số dòng bị xoá do thiếu/trùng order_id (PK): {n_before - len(df_orders)}")

df_orders = df_orders.reset_index(drop=True)

# order_date: parse ngày, thiếu thì lấp bằng ffill/bfill (đơn hàng gần đó thời gian gần nhất)
df_orders["order_date"] = pd.to_datetime(df_orders["order_date"], errors="coerce")
n_missing_date = df_orders["order_date"].isna().sum()
if n_missing_date > 0:
    df_orders["order_date"] = df_orders["order_date"].ffill().bfill()
    print(f"order_date thiếu {n_missing_date} giá trị -> đã lấp bằng ffill/bfill")
df_orders["order_date"] = df_orders["order_date"].dt.strftime("%Y-%m-%d")

# Các cột phân loại: thiếu thì lấp bằng mode()
categorical_cols = ["order_status", "payment_method", "device_type", "order_source"]
for col in categorical_cols:
    df_orders[col] = df_orders[col].astype(str).str.strip().str.lower().replace({"nan": np.nan, "": np.nan})
    n_missing = df_orders[col].isna().sum()
    if n_missing > 0:
        mode_val = df_orders[col].mode(dropna=True)[0]
        df_orders[col] = df_orders[col].fillna(mode_val)
        print(f"{col} thiếu {n_missing} giá trị -> đã lấp bằng mode ('{mode_val}')")

# customer_id, zip, sales_employee_id là ID/FK -> lấp bằng
# ffill/bfill (giữ nguyên bản chất "chuỗi ID" thay vì suy ra từ trung bình/mode)
for col in ["customer_id", "zip", "sales_employee_id"]:
    n_missing = df_orders[col].isna().sum()
    if n_missing > 0:
        df_orders[col] = df_orders[col].ffill().bfill()
        print(f"{col} thiếu {n_missing} giá trị -> đã lấp bằng ffill/bfill")

# comment: null nghĩa là không để lại bình luận -> điền chuỗi rỗng
df_orders["comment"] = df_orders["comment"].fillna("").astype(str).str.strip()

# Đối chiếu chéo với bảng khác
try:
    df_customers_ref = pd.read_csv("customers.csv")
    zip_map = df_customers_ref.set_index("customer_id")["zip"]
    correct_zip = df_orders["customer_id"].map(zip_map)
    n_mismatch = (correct_zip.notna() & (df_orders["zip"] != correct_zip)).sum()
    if n_mismatch > 0:
        df_orders.loc[correct_zip.notna(), "zip"] = correct_zip[correct_zip.notna()]
        print(f"zip khác với customers.csv -> đã sửa lại theo customers.csv: {n_mismatch} dòng")
    else:
        print("zip khớp 100% với customers.csv")
except FileNotFoundError:
    print("Không tìm thấy customers.csv, bỏ qua bước đối chiếu zip")

# Final check
print("=" * 50)
print("KIỂM TRA CUỐI CÙNG")
print("=" * 50)
silver_cols = ["order_id", "customer_id", "zip", "sales_employee_id",
               "order_date", "order_status", "device_type", "order_source", "comment"]
df_orders_silver = df_orders[silver_cols].copy()
print(df_orders_silver.isna().sum())
print()
print(f"Tổng số dòng: {len(df_orders_silver)}")
df_orders_silver.head()

# Xuất file csv
df_orders_silver.to_csv("orders_enriched.csv", index=False)