# -*- coding: utf-8 -*-
"""payments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LUlc_q3KzSgOfeLtzd4r-qiKHzBOUbz
"""

import pandas as pd
import numpy as np

# Đọc file
df_pay = pd.read_csv("payments.csv")

# Đọc thử dữ liệu
df_pay.info()
df_pay.isna().sum()

# Xoá dòng rỗng hoàn toàn
n_before = len(df_pay)
df_pay = df_pay.dropna(how="all")
print(f"Số dòng rỗng hoàn toàn (đã xoá): {n_before - len(df_pay)}")

# Xoá dòng trùng hoàn toàn
n_before = len(df_pay)
df_pay = df_pay.drop_duplicates()
print(f"Số dòng trùng lặp toàn bộ (đã xoá): {n_before - len(df_pay)}")

# order_id là PK -> thiếu thì phải xoá, trùng thì giữ bản đầu
n_before = len(df_pay)
df_pay = df_pay.dropna(subset=["order_id"])
df_pay = df_pay.drop_duplicates(subset="order_id", keep="first")
print(f"Số dòng bị xoá do thiếu/trùng order_id (PK): {n_before - len(df_pay)}")

df_pay = df_pay.reset_index(drop=True)

# payment_method: phân loại -> lấp bằng mode() nếu thiếu
df_pay["payment_method"] = df_pay["payment_method"].astype(str).str.strip().str.lower().replace({"nan": np.nan})
n_missing_pm = df_pay["payment_method"].isna().sum()
if n_missing_pm > 0:
    mode_val = df_pay["payment_method"].mode(dropna=True)[0]
    df_pay["payment_method"] = df_pay["payment_method"].fillna(mode_val)
    print(f"payment_method thiếu {n_missing_pm} giá trị -> đã lấp bằng mode ('{mode_val}')")

# payment_value: số tiền -> lấp bằng median() nếu thiếu
n_missing_val = df_pay["payment_value"].isna().sum()
if n_missing_val > 0:
    df_pay["payment_value"] = df_pay["payment_value"].fillna(df_pay["payment_value"].median())
    print(f"payment_value thiếu {n_missing_val} giá trị -> đã lấp bằng median")

# installments: số lần trả góp (số nguyên rời rạc) -> lấp bằng median rồi làm tròn
n_missing_inst = df_pay["installments"].isna().sum()
if n_missing_inst > 0:
    med_inst = round(df_pay["installments"].median())
    df_pay["installments"] = df_pay["installments"].fillna(med_inst)
    print(f"installments thiếu {n_missing_inst} giá trị -> đã lấp bằng median ({med_inst})")
df_pay["installments"] = df_pay["installments"].astype(int)

# Giá trị bất thường (chỉ in ra để biết, không tự sửa vì có thể là lỗi nhập liệu thật)
n_bad_value = (df_pay["payment_value"] <= 0).sum()
n_bad_inst = (df_pay["installments"] <= 0).sum()
print(f"payment_value <= 0: {n_bad_value} | installments <= 0: {n_bad_inst}")

# ĐỐI CHIẾU CHÉO VỚI CÁC BẢNG LIÊN QUAN
try:
    df_orders_ref = pd.read_csv("orders_enriched.csv")
    n_orphan_order = (~df_pay["order_id"].isin(df_orders_ref["order_id"])).sum()
    print(f"order_id không tồn tại trong orders_enriched: {n_orphan_order}")

    df_orders_ref["payment_method"] = df_orders_ref["payment_method"].astype(str).str.strip().str.lower()
    m = df_pay.merge(df_orders_ref[["order_id", "payment_method"]], on="order_id",
                      suffixes=("_pay", "_orders"), how="left")
    n_mismatch_pm = (m["payment_method_pay"] != m["payment_method_orders"]).sum()
    print(f"payment_method khác với orders_enriched (chỉ để biết, không tự sửa vì không rõ nguồn nào đúng hơn): {n_mismatch_pm}")
except FileNotFoundError:
    print("Không tìm thấy orders_enriched.csv, bỏ qua đối chiếu")

try:
    df_items_ref = pd.read_csv("order_items.csv")
    line_total = (df_items_ref["quantity"] * df_items_ref["unit_price"] - df_items_ref["discount_amount"]).groupby(df_items_ref["order_id"]).sum()
    cmp = df_pay.set_index("order_id")["payment_value"].reindex(line_total.index)
    diff = (cmp - line_total).abs()
    n_diff = (diff > 1).sum()
    print(f"payment_value lệch > 1 đơn vị so với tổng order_items: {n_diff}")
except FileNotFoundError:
    print("Không tìm thấy order_items.csv, bỏ qua đối chiếu payment_value")

# Final check
print("=" * 50)
print("KIỂM TRA CUỐI CÙNG")
print("=" * 50)
silver_cols = ["order_id", "payment_method", "payment_value", "installments"]
df_pay_silver = df_pay[silver_cols].copy()
print(df_pay_silver.isna().sum())
print()
print(f"Tổng số dòng: {len(df_pay_silver)}")
df_pay_silver.head()

# Xuất file csv
df_pay_silver.to_csv("payments.csv", index=False)