# -*- coding: utf-8 -*-
"""sales_employees.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LUlc_q3KzSgOfeLtzd4r-qiKHzBOUbz
"""

import pandas as pd
import numpy as np

# Đọc file gốc, chỉ lấy các cột liên quan tới nhân viên
df_orders_raw = pd.read_csv("orders_enriched.csv")
emp_cols = ["sales_employee_id", "sales_employee_name", "marital_status",
            "education_level", "years_experience"]
df_emp = df_orders_raw[emp_cols].copy()

df_emp.info()
df_emp.isna().sum()

# Dòng rỗng hoàn toàn -> xoá
n_before = len(df_emp)
df_emp = df_emp.dropna(how="all")
print(f"Số dòng rỗng hoàn toàn (đã xoá): {n_before - len(df_emp)}")

# sales_employee_id là PK -> thiếu thì xoá
n_before = len(df_emp)
df_emp = df_emp.dropna(subset=["sales_employee_id"])
print(f"Số dòng thiếu sales_employee_id (đã xoá): {n_before - len(df_emp)}")

df_emp = df_emp.reset_index(drop=True)

# Lấp dữ liệu thiếu cho từng thuộc tính
if df_emp["years_experience"].isna().sum() > 0:
    n_missing = df_emp["years_experience"].isna().sum()
    df_emp["years_experience"] = df_emp["years_experience"].fillna(df_emp["years_experience"].median())
    print(f"years_experience thiếu {n_missing} giá trị -> đã lấp bằng median")

for col in ["marital_status", "education_level", "sales_employee_name"]:
    if df_emp[col].isna().sum() > 0:
        n_missing = df_emp[col].isna().sum()
        df_emp[col] = df_emp[col].fillna(df_emp[col].mode()[0])
        print(f"{col} thiếu {n_missing} giá trị -> đã lấp bằng mode")

# KIỂM TRA TÍNH NHẤT QUÁN: 1 sales_employee_id phải có đúng 1 bộ thuộc tính
# (đây là thuộc tính của NHÂN VIÊN, không phải của ĐƠN HÀNG)
attr_cols = ["sales_employee_name", "marital_status", "education_level", "years_experience"]
n_unique_per_emp = df_emp.groupby("sales_employee_id")[attr_cols].nunique()
inconsistent_ids = n_unique_per_emp[(n_unique_per_emp > 1).any(axis=1)].index.tolist()
print(f"Số nhân viên có thuộc tính KHÔNG nhất quán giữa các đơn hàng: {len(inconsistent_ids)}")
if inconsistent_ids:
    print(f"-> Với các trường hợp này, lấy giá trị xuất hiện nhiều nhất (mode) khi gộp về 1 dòng/nhân viên: {inconsistent_ids[:20]}")

# RÚT GỌN VỀ 1 DÒNG / 1 NHÂN VIÊN (đúng cấp độ chi tiết của bảng SALES_EMPLOYEES)
df_sales_employees_silver = df_emp.groupby("sales_employee_id", as_index=False).agg({
    "sales_employee_name": lambda s: s.mode().iat[0],
    "marital_status": lambda s: s.mode().iat[0],
    "education_level": lambda s: s.mode().iat[0],
    "years_experience": lambda s: s.mode().iat[0],
})

# Final check
print("=" * 50)
print("KIỂM TRA CUỐI CÙNG")
print("=" * 50)
print(df_sales_employees_silver.isna().sum())
print()
print(f"Số nhân viên duy nhất (số dòng silver): {len(df_sales_employees_silver)}")
df_sales_employees_silver.head()

# Xuất file csv
df_sales_employees_silver.to_csv("sales_employees.csv", index=False)