# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P32XuhlJRE72liZHYs8C6neqZX2E3z3R
"""

import pandas as pd
import numpy as np

# ============================================================
# 1. ĐỌC DỮ LIỆU
# ============================================================
df_customers = pd.read_csv("customers.csv")

print("Kích thước ban đầu:", df_customers.shape)
print("\nSố lượng giá trị null:")
print(df_customers.isnull().sum())


# ============================================================
# 2. XÓA DÒNG NULL HOÀN TOÀN
# ============================================================
before = len(df_customers)

df_customers = df_customers.dropna(how="all").copy()

print("\nSố dòng null hoàn toàn đã xóa:", before - len(df_customers))


# ============================================================
# 3. LÀM SẠCH CỘT TEXT
# ============================================================
text_columns = [
    "city",
    "gender",
    "age_group",
    "acquisition_channel"
]

for col in text_columns:
    df_customers[col] = df_customers[col].astype("string").str.strip()


# ============================================================
# 4. CHUẨN HÓA CUSTOMER_ID
# ============================================================
df_customers["customer_id"] = pd.to_numeric(
    df_customers["customer_id"],
    errors="coerce"
)

# Nếu customer_id bị thiếu thì không tự tạo ID mới
# vì đây là khóa chính, không thể suy đoán chính xác.


# ============================================================
# 5. CHUẨN HÓA ZIP CODE
# ============================================================
df_customers["zip"] = pd.to_numeric(
    df_customers["zip"],
    errors="coerce"
)

# ZIP được lưu dưới dạng chuỗi 5 ký tự
# để không làm mất số 0 ở đầu.
df_customers["zip"] = (
    df_customers["zip"]
    .astype("Int64")
    .astype("string")
    .str.zfill(5)
)


# ============================================================
# 6. CHUẨN HÓA SIGNUP_DATE
# ============================================================
df_customers["signup_date"] = pd.to_datetime(
    df_customers["signup_date"],
    errors="coerce"
)

# Nếu ngày không hợp lệ -> thay bằng ngày trung vị
valid_dates = df_customers["signup_date"].dropna()

if len(valid_dates) > 0:
    median_date = valid_dates.sort_values().iloc[len(valid_dates) // 2]
    df_customers["signup_date"] = df_customers["signup_date"].fillna(
        median_date
    )


# ============================================================
# 7. CHUẨN HÓA GENDER
# ============================================================
valid_gender = [
    "Female",
    "Male",
    "Non-binary"
]

invalid_gender = ~df_customers["gender"].isin(valid_gender) & \
                 df_customers["gender"].notna()

print("Gender không hợp lệ:", invalid_gender.sum())

# Không xóa dữ liệu -> thay bằng giá trị xuất hiện nhiều nhất
gender_mode = df_customers.loc[
    df_customers["gender"].isin(valid_gender),
    "gender"
].mode()

if len(gender_mode) > 0:
    df_customers.loc[invalid_gender, "gender"] = gender_mode.iloc[0]
    df_customers["gender"] = df_customers["gender"].fillna(
        gender_mode.iloc[0]
    )


# ============================================================
# 8. CHUẨN HÓA AGE_GROUP
# ============================================================
valid_age_group = [
    "18-24",
    "25-34",
    "35-44",
    "45-54",
    "55+"
]

invalid_age = ~df_customers["age_group"].isin(valid_age_group) & \
              df_customers["age_group"].notna()

print("Age group không hợp lệ:", invalid_age.sum())

age_mode = df_customers.loc[
    df_customers["age_group"].isin(valid_age_group),
    "age_group"
].mode()

if len(age_mode) > 0:
    df_customers.loc[invalid_age, "age_group"] = age_mode.iloc[0]
    df_customers["age_group"] = df_customers["age_group"].fillna(
        age_mode.iloc[0]
    )


# ============================================================
# 9. CHUẨN HÓA ACQUISITION_CHANNEL
# ============================================================
valid_channels = [
    "organic_search",
    "social_media",
    "paid_search",
    "email_campaign",
    "referral",
    "direct"
]

invalid_channel = ~df_customers["acquisition_channel"].isin(
    valid_channels
) & df_customers["acquisition_channel"].notna()

print("Acquisition channel không hợp lệ:",
      invalid_channel.sum())

channel_mode = df_customers.loc[
    df_customers["acquisition_channel"].isin(valid_channels),
    "acquisition_channel"
].mode()

if len(channel_mode) > 0:
    df_customers.loc[
        invalid_channel,
        "acquisition_channel"
    ] = channel_mode.iloc[0]

    df_customers["acquisition_channel"] = (
        df_customers["acquisition_channel"]
        .fillna(channel_mode.iloc[0])
    )


# ============================================================
# 10. KIỂM TRA CUỐI
# ============================================================
print("\n===== KIỂM TRA CUSTOMERS SAU KHI LÀM SẠCH =====")
print("Kích thước:", df_customers.shape)
print("\nNull:")
print(df_customers.isnull().sum())

print("\nDuplicate:", df_customers.duplicated().sum())
print("Duplicate customer_id:",
      df_customers["customer_id"].duplicated().sum())


# ============================================================
# 11. XUẤT FILE CSV
# ============================================================
df_customers.to_csv(
    "customers_silver.csv",
    index=False
)

print("\nĐã xuất: customers_silver.csv")




